applicationTitle: Taco2036
shadowMask: aperture-grille
blur: false 
bezel: flat 
startUnmuted: true

noSignalContent: # Optional. You can specify content to show when a channel is off the air.
  image: nosignal_screen.png
  backgroundAudio: https://file.garden/aUYIWVAKvQxCBY-_/music/Account_Organism.mp3

osd:
  theme: digital # old comcast ahh


channels:

- number: 1
  name: Welcome
  abbr: HELLO
  title: Taco2036
  description: Thanks for visiting Taco2036!
  image: /welcome.png
  backgroundAudio: https://file.garden/aUYIWVAKvQxCBY-_/music/2003%20Weatherscan%20Track%208.mp3

- number: 2
  name: Google Nexus Uploads
  title: Nexus
  description: Watch videos of Google's Discontinued Nexus Devices
  abbr: NXS
  youtube-playlist:
    src: UUUjlPym2cxucUVPdE8kYOOg
    shuffle: true
  
- number: 3
  name: Program Guide
  abbr: GUIDE
  title: Guide
  noise: 0.1
  v-split:
  a:
    youtube-playlist:
     src: UUUjlPym2cxucUVPdE8kYOOg
     shuffle: true
  b:
   guide:
       alerts:
         - position: 6
           text: |
              I HAVE CONSUMED 67 METAL PIPES JR.

- number: 4
  name: Keno
  abbr: KENO1
  title: ONLY KENO!
  description: ONLY KENO - By Bubble Bass AKA Bubble Ass
  backgroundAudio: https://taco2036.github.io/music.pls
  backgroundAudioOptions:
   shufflePlaylist: true
  keno:
   drawingMinutes: 10
   drawIntervalMs: 10000
   centerText: ONLY KENO - That's ass Folks!

- number: 5
  name: Keno 2
  title: ONLY KENO!
  abbr: KENO2
  description: ONLY KENO - By Bubble Bass AKA Bubble Ass
  backgroundAudio: https://taco2036.github.io/music.pls
  backgroundAudioOptions:
   shufflePlaylist: true
  keno:
   drawingMinutes: 20
   drawIntervalMs: 5000
   centerText: ONLY KENO - BOMB PIZDA


- number: 6
  name: SML Uploads
  title: SML
  description: Logan Thirtyacre's Popular Channel Videos
  abbr: SML
  youtube-playlist:
    src: UUnSWkrRWNQWNhDusoWr_HXQ
    shuffle: true

- number: 7
  name: June 12 2009
  title: J12 2009
  description: Analog TV Shutdown
  abbr: ATV
  youtube-playlist:
    src: PL8fAhLpxoiJRqqdLTNy2ndLzMYYt5HXdJ
    shuffle: true

