applicationTitle: GAMATE CABLE


osd:
  theme: sat2007
  aspectRatioBehavior: stretch
  themeOptions: # certain themes have additional options that can be set like this:
  showMessageIcon: true # Show the message icon in the top bar
  showChannelLockIcon: true # Show the channel lock icon in the top bar



##### CHANNELS #####
# REFERENCE:
# https://greenhillplaza.notion.site/Television-Simulator-99-c28584f069b94f58a71b5c9fe2484dcb#8969cd7aff0e4d569efa77b15cbacf51
#
# The rest of this file is about defining a channel lineup.
####################

# noSignalContent: # Optional. You can specify content to show when a channel is off the air.
#   image: placeholders/no-signal.png

defaultChannel: 2 # Required. The default channel to start on when visiting the page.

channels: # starts a list of channels. Every channel below begins with a "-" as that lets YAML know we're defining a list.

- number: 1 # Required. Every channel needs a unique number. Negative numbers indicate line inputs, so -1 will be displayed as "LINE 1". Channel 0 is displayed as the TV's "MENU".
  name: On Demand # Required. The name of the channel.
  abbr: ON # Required. An abbreviation for the channel; try to keep it short.
  image: placeholders/channel-1.png # Channel content. If there's none the TV will play static. There are various content engines available with lots of different configurations. In this case it's an image.
  backgroundAudio: placeholders/bgm-3.mp3 # Optional. You can add background audio to any channel. This works well with radio streams, but you could use any audio file that the browser supports too.

# In YAML the indentation of things matters; keep it consistent and you should be good. In this file I'm using two spaces for tabs. Your editor may do things differently so watch out for that!

- number: 2
  name: VOLTIX
  abbr: VTX
  video: https://rhine.webchnl.live/memfs/a5ebeea5-d842-43ae-add9-290d59f5593e.m3u8
  icon: https://webchnl.com/assets/img/channelicons/voltix.png