applicationTitle: Taco2036
shadowMask: aperture-grille
blur: false 
bezel: flat 
startUnmuted: true

dimensions:
  screenWidth: 800 
  screenHeight: 600

osd:
  theme: digital # 1990's analog C-band satellite receiver theme


channels:

- number: 1
  name: Welcome
  abbr: HELLO
  title: Public Beta Testing # Optional. Title to show in the channel guides, including program guide channels and in the digital cable theme's on-screen guide.
  description: Thanks for testing Television Simulator '99 v2, Public Beta! # Optional. Description to show in the guide.
  image: /welcome.png
  backgroundAudio: /placeholders/bgm-2.mp3

- number: 2
  name: You're watching Television Simulator
  abbr: TVS
  video: placeholders/tvs-loop.mp4
  backgroundAudio: /content/bgm-4.mp3

- number: 3
  name: TVS Update News
  abbr: NEWS
  feed-reader:
    src: https://docs.tvs.gcpw.art/tvs-changelog.xml
    title: TVS Update News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 4
  name: Program Guide
  abbr: GUIDE
  title: Prevue Guide
  noise: 0.1
  v-split:
    a:
      h-split:
        a:
          basic-text:
            src: https://taco2036.github.io/guide-ads.json
            autoAdvance: true
        b:
          youtube-playlist:
            src: UUUjlPym2cxucUVPdE8kYOOg
            shuffle: true
    b:
      guide:
        logo: placeholders/guide-header.png
        alerts:
          - position: 6
            text: |
              I HAVE CONSUMED 67 METAL PIPES JR.
